Developer/MVC Project/Areas/API/Controllers/ListingController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using RainWorx.FrameWorx.Clients;
using RainWorx.FrameWorx.DTO;
using RainWorx.FrameWorx.DTO.FaultContracts;
using RainWorx.FrameWorx.MVC.Areas.API.Controllers.Base;
using RainWorx.FrameWorx.MVC.Areas.API.Controllers.Helpers;
using RainWorx.FrameWorx.MVC.Areas.API.Models;
using RainWorx.FrameWorx.Utility;

//using RainWorx.FrameWorx.WebAPI.Models;

namespace RainWorx.FrameWorx.MVC.Areas.API.Controllers
{
    /// <summary>
    /// Provides services to Create/Update/Get/Delete Listings
    /// </summary>
    [RoutePrefix("api/listing")]
    public class ListingController : AuctionWorxAPIController
    {
        /// <summary>
        /// Gets a listing by ID
        /// </summary>
        /// <param name="id">The ID of the listing to get</param>
        /// <returns>An HTTP Status code of 200 (OK) and the Listing on success.  Otherwise, HTTP Status code 404 (Not Found) if the Listing is not found.</returns>
        [Route("{id}")]
        [ResponseType(typeof(APIListing))]
        public HttpResponseMessage Get(int id)
        {
            try
            {
                string userName = Request.GetUserName();
                DTO.Listing listing = ListingClient.GetListingByIDWithFillLevel(userName, id, Strings.ListingFillLevels.Default);
                APIListing smallListing = APIListing.FromDTOListing(listing);
                Utilities.PruneListingCustomFieldsVisbility(ref smallListing, userName);
                return Request.CreateResponse<APIListing>(HttpStatusCode.OK, smallListing);
            }
            catch (System.ServiceModel.FaultException<InvalidArgumentFaultContract> iafc)
            {
                //let the redirect below handle the "Listing doesn't exist" error, otherwise re-throw the exception
                if (iafc.Detail.Reason != ReasonCode.ListingNotExist) throw iafc;
                return Request.CreateErrorResponse(HttpStatusCode.NotFound, "Listing not found");
            }
        }

        /// <summary>
        /// Searches for listings
        /// </summary>        
        /// <param name="page">The zero-based page number to retrieve</param>
        /// <param name="size">The size of a single page</param>
        /// <returns>An HTTP Status code of 200 (OK) and the Listing on success.  Otherwise, HTTP Status code 404 (Not Found) if the Listing is not found.</returns>
        [Route("search/{page}/{size}")]
        [ResponseType(typeof(Page<APIListing>))]
        public HttpResponseMessage GetSearchListings(int page, int size)
        {
            string userName = Request.GetUserName();

            ListingPageQuery query = new ListingPageQuery();
            query.Descending = true;
            query.Index = 0;
            query.Name = "Search";
            query.Input = new UserInput(userName, userName);
            query.Input.Items = Request.GetQueryNameValuePairs()
                .ToDictionary((keyItem) => keyItem.Key, (valueItem) => valueItem.Value);

            Page<Listing> results = ListingClient.SearchListings(userName, query, page, size);

            User user = UserClient.GetUserByUserName(userName, userName);

            Page<APIListing> retVal = new Page<APIListing>(new List<APIListing>(results.List.Count), results.PageIndex,
                results.PageSize, results.TotalItemCount, results.SortExpression);
            foreach (Listing listing in results.List)
            {
                APIListing smallListing = APIListing.FromDTOListing(listing);
                Utilities.PruneListingCustomFieldsVisbility(ref smallListing, user);
                retVal.List.Add(smallListing);
            }

            return Request.CreateResponse<Page<APIListing>>(HttpStatusCode.OK, retVal);
        }

        /// <summary>
        /// Creates a Listing
        /// </summary>
        /// <param name="input">A UserInput object containing the data with which to create the Listing</param>
        /// <returns>An HTTP Status code of 201 (Created) upon success, with the Location response header set to the location of the newly created Listing (the GET resource).</returns>
        [Route("")]
        [ResponseType(typeof(string))]
        public HttpResponseMessage Post([FromBody] UserInput input)
        {
            if (input == null) return Request.CreateErrorResponse(HttpStatusCode.BadRequest, "UserInput is null");
            int newListingID;

            if (!input.Items.ContainsKey("AllCategories") || string.IsNullOrEmpty(input.Items["AllCategories"]))
            {
                var lineages = new List<string>();
                int categoryID = 0;
                if (input.Items.ContainsKey("CategoryID") && int.TryParse(input.Items["CategoryID"], out categoryID) && categoryID > 0)
                {
                    lineages.Add(CommonClient.GetCategoryPath(categoryID).Trees[categoryID].LineageString);
                }
                int regionID = 0;
                if (input.Items.ContainsKey("RegionID") && int.TryParse(input.Items["RegionID"], out regionID) && regionID > 0)
                {
                    lineages.Add(CommonClient.GetCategoryPath(regionID).Trees[regionID].LineageString);
                }
                if (lineages.Count > 0)
                {
                    string categories = Hierarchy<int, Category>.MergeLineageStrings(lineages);
                    input.Items.Add(Strings.Fields.AllCategories, categories);
                }
            }

            ListingClient.CreateListing(Request.GetUserName(), input, false, out newListingID);
            return Request.Created(newListingID);
        }

        /// <summary>
        /// Deletes a Listing.
        /// </summary>
        /// <param name="id">The ID of the Listing to delete</param>
        /// <returns>An HTTP Status code of 204 (No Content) upon success.</returns>
        [Route("{id}")]
        public HttpResponseMessage Delete(int id)
        {
            try
            {
                ListingClient.DeleteListing(Request.GetUserName(), id);
            }
            catch (System.ServiceModel.FaultException<InvalidArgumentFaultContract> iafc)
            {
                if (iafc.Detail.Reason != ReasonCode.ListingNotExist) throw iafc;
            }
            return Request.CreateResponse(HttpStatusCode.NoContent);
        }

        /// <summary>
        /// Updates a Listing
        /// </summary>
        /// <param name="input">A UserInput object containing the data with which to update the Listing</param>
        /// <returns>An HTTP Status code of 204 (No Content) upon success.</returns>
        [Route("")]
        public HttpResponseMessage Put([FromBody] UserInput input)
        {
            string username = Request.GetUserName();

            int listingID = 0;
            if (input.Items.ContainsKey("ListingID") && int.TryParse(input.Items["ListingID"], out listingID))
            {
                //listing ID specified properly
                DTO.Listing listing;
                try
                {
                    listing = ListingClient.GetListingByIDWithFillLevel(username, listingID, Strings.ListingFillLevels.Default);
                }
                catch (System.ServiceModel.FaultException<InvalidArgumentFaultContract> iafc)
                {
                    //let the redirect below handle the "Listing doesn't exist" error, otherwise re-throw the exception
                    if (iafc.Detail.Reason != ReasonCode.ListingNotExist) throw iafc;
                    return Request.CreateErrorResponse(HttpStatusCode.NotFound, "Listing not found");
                }

                ListingClient.UpdateListingWithUserInput(username, listing, input);
                return Request.CreateResponse(HttpStatusCode.NoContent);
            }
            else
            {
                //listing ID missing or not specified properly
                return Request.CreateResponse(HttpStatusCode.BadRequest,
                                              new ErrorResponse()
                                                  {
                                                      Message =
                                                          "ListingID missing from UserInput or not convertable to an int."
                                                  });
            }
        }

        /// <summary>
        /// Retrieves all registered listing types
        /// </summary>
        /// <returns>a list of listing types</returns>
        [Route("types")]
        [ResponseType(typeof(List<ListingType>))]
        public HttpResponseMessage GetListingTypes()
        {
            return Request.CreateResponse(HttpStatusCode.OK, ListingClient.ListingTypes);
        }

        /// <summary>
        /// Retrieves all properties for a provided listing type name
        /// </summary>        
        /// <param name="name">The name of the listing type to get properties for</param>
        /// <returns>A list of CustomProperties for the specified listing type</returns>
        [Route("type/{name}")]
        [ResponseType(typeof(List<CustomProperty>))]
        public HttpResponseMessage GetListingTypeProperties(string name)
        {
            return Request.CreateResponse(HttpStatusCode.OK, ListingClient.GetListingTypeProperties(name, "Site"));
        }
    }
}

Developer/MVC Project/Views/Listing/Action_Login.cshtml
@model Listing

<div class="btn-group pull-right">
    <button type="button" class="btn btn-default btn-xs btn-block dropdown-toggle" data-toggle="dropdown">
        &nbsp;&nbsp; @Html.GlobalResource("ListingOptions_small") &nbsp;
        <span class="caret"></span>&nbsp;&nbsp;
    </button>
    <ul class="dropdown-menu" role="menu">
        <li>
            @Html.ActionLink(Html.GlobalResource("SignIn"), MVC.LogOnAction, MVC.AccountController,
                new { returnUrl = Model.GetDetailUrl() }, null)
        </li>
    </ul>
</div>

Developer/MVC Project/Views/Listing/Action_SellerNotOwner.cshtml
@model Listing

<div class="btn-group pull-right">
    <button type="button" class="btn btn-default btn-xs btn-block dropdown-toggle" data-toggle="dropdown">
        &nbsp;&nbsp; @Html.GlobalResource("ListingOptions_small") &nbsp;
        <span class="caret"></span>&nbsp;&nbsp;
    </button>
    <ul class="dropdown-menu" role="menu">
        @if (SiteClient.UserMessagingEnabled)
        {
            <li>
                @Html.ActionLink(Html.GlobalResource("Contact"), MVC.SendListingMessageAction, MVC.AccountController,
                    new
                    {
                        receiver = Model.OwnerUserName,
                        template = Templates.AskListingQuestion,
                        listingID = Model.ID,
                        returnUrl = Model.GetDetailUrl()
                    }, null)
            </li>
        }
        @if (Model.Context.Watched)
        {
            <li><a class="alert-success">@Html.GlobalResource("CurrentlyWatching")</a></li>
        }
        else
        {
            <li>@Html.ActionLink(Html.GlobalResource("WatchItem"), MVC.AddWatchAction, new { id = Model.ID }, null)</li>
        }
    </ul>
</div>

Developer/MVC Project/Views/Listing/AuctionDetails.cshtml
@model Listing
<script type="text/javascript">
    $(document).ready(function () {
        if ($.cookie('currency') == '@Model.Currency.Code') {
            $("#convertedprice").hide();
        } else {
            $("#convertedprice").show();
        }
    });


</script>
@if ((Model.Status == ListingStatuses.Successful) || (Model.Status == ListingStatuses.Unsuccessful))
{
    <div class="panel panel-default closed-details">
        <ul class="list-group">
            <li class="list-group-item">
                @if (Model.Status == ListingStatuses.Successful)
                {
                    <span class="sold pull-right">@Html.GlobalResource("Sold")</span>
                    @Html.Resource("AuctionListing, FinalPriceXSuccessful", Html.LocalCurrencyWithNumberTags(Model.CurrentPrice.Value, Model.Currency.Code))
                }
                else if (Model.AcceptedListingActionCount() == 0)
                {
                    @Html.Resource("AuctionListing, StartingBidX", Html.LocalCurrencyWithNumberTags(Model.OriginalPrice.Value, Model.Currency.Code))
                }
                else
                {
                    @Html.Resource("AuctionListing, FinalPriceXUnsuccessful", Html.LocalCurrencyWithNumberTags(Model.CurrentPrice.Value, Model.Currency.Code))
                }
            </li>
            @if ((Model.CurrentListingAction != null) || (Model.Status == ListingStatuses.Successful))
            {
                <li class="list-group-item">
                    @Html.Resource("AuctionListing, XBids", Model.AcceptedListingActionCount())
                    <a href="@Url.Action(MVC.HistoryAction, "Listing", new { id = Model.ID, currency = Model.Currency.Code})" class="pull-right">
                        @Html.Resource("AuctionListing, ViewHistory")
                    </a>
                </li>
            }
            else
            {
                <li class="list-group-item">
                    @Html.Resource("AuctionListing, XBids", Model.AcceptedListingActionCount())
                    @if (!string.IsNullOrWhiteSpace(Model.Properties.Where(p => p.Field.Name.Equals(Fields.ReservePrice)).Single().Value))
                    {
                        <span class="reserve-not-met awe-rt-ReserveStatus">@Html.Resource("AuctionListing, " + (string)ViewData["ReserveStatus"])</span>
                    }
                </li>
            }
            @{
                var showUserNames = bool.Parse(SiteClient.Settings["ShowBidHistoryUserNames"]);
                bool anAdmin = User.IsInRole("Admin");
                if (Model.CurrentListingAction != null && (showUserNames || anAdmin))
                {
                    <li class="list-group-item">
                        @Html.Resource("AuctionListing, HighBidderX", Model.CurrentListingAction.UserName)
                    </li>
                }
            }
        </ul>
    </div>
                }
@{
    bool showSellerData = bool.Parse(SiteClient.Settings["SellerUsernameDetailPage"]);
    bool paymentsEnabled = (Model.Owner.CreditCardAccepted() && SiteClient.BoolSetting(SiteProperties.AuthorizeNet_Enabled)) ||
        (Model.Owner.BoolProperty(StdUserProps.StripeConnect_SellerAccountConnected) && SiteClient.BoolSetting(SiteProperties.StripeConnect_Enabled)) ||
        (Model.OwnerAcceptsPayPal() && SiteClient.BoolSetting(SiteProperties.PayPal_Enabled));
    bool hasShipping = Model.ShippingOptions.Count > 0;
    bool hasPaymentInstructions = !string.IsNullOrEmpty(Model.PaymentInstructions());

    if (showSellerData || paymentsEnabled || hasShipping || hasPaymentInstructions)
    {
        string sellerPaymentData = "seller-data__payment";
        if (!showSellerData)
        {
            sellerPaymentData += "  seller-data__fullwidth";
        }
        <div class="detail__seller-data">
            <div class="seller-data__container">
                @{
                    if (showSellerData)
                    {
                        <div class="seller-data__summary">
                            @Html.Partial("ListingDetail_SellerUserSummary")
                        </div>
                    }
                }
                <div class="@sellerPaymentData">
                    @Html.Partial("AuctionPaymentOptions")
                </div>
            </div>
            @Html.Partial("ShippingOptionDisplay")
        </div>
                    }
}

<script type="text/javascript">
    var reserveStatus = {};
    var buyNowPriceForJS = "";
    @if (User.Identity.IsAuthenticated && Model.ListingActions.Any(la => la.UserName == Html.FBOUserName() && la.Status == "Accepted"))
        {
            <text>var anyActivity = true;</text>
        }
        else
        {
            <text>var anyActivity = false;</text>
        }


    $(document).ready(function () {
        $(document).on("SignalR_ListingActionResponse", function (event, data) {
            if ($.inArray(data.Action_ListingID, interestingListings) >= 0) {
                if (data.Accepted) {
                    anyActivity = true;
                }
            }
        });

        //when this auction's price changes
        $(document).on("SignalR_UpdateListingAction", function (event, data) {
            //handle Custom Updates Status Changes
            var buyNowAvailable = data.Properties["BuyNowStatus"] == "true";
            var buyNowPrice = data.Properties["BuyNowPrice"];
            var reserveDefined = data.Properties["ReserveDefined"] == "true";
            var reserveMet = data.Properties["ReserveMet"] == "true";
            var makeOfferAvailable = data.Properties["MakeOfferStatus"] == "true";

            //update reserve status
            if (reserveDefined) {
                if (reserveMet) {
                    $(".awe-rt-ReserveStatus").html(reserveStatus["ReserveMet"]);
                } else {
                    $(".awe-rt-ReserveStatus").html(reserveStatus["ReserveNotMet"]);
                }
            } else {
                $(".awe-rt-ReserveStatus").html(reserveStatus["NoReserve"]);
            }
            $(".awe-rt-ReserveStatus").pulse();

            //update Buy Now Status
            if (buyNowAvailable) {
                $(".awe-rt-BuyItNowContainer").show();
                $(".awe-rt-BuyItNowAvailable").pulse();
                $(".awe-rt-BuyNowPrice").pulse();
            } else {
                $(".awe-rt-BuyItNowContainer").hide();
            }

            //update Make Offer Status
            if (makeOfferAvailable) {
                $(".awe-rt-MakeOfferContainer").show();
                $("#MakeOffer").pulse();
            } else {
                $(".awe-rt-MakeOfferContainer").hide();
            }

            //update Buy Now Price
            $('.awe-rt-BuyNowPrice span.NumberPart').each(function () {
                buyNowPriceForJS = Globalize.formatNumber(parseFloat(buyNowPrice), { minimumFractionDigits: 2, maximumFractionDigits: 2 });
                $(this).html(buyNowPriceForJS);
                $(this).pulse();
            });

            //if # of bids is > 0
            if (data.AcceptedActionCount > 0) {
                //show bid history button and high bidder
                $(".BidHistoryButton").removeClass("awe-hidden");
                $(".HighBidder").html(data.CurrentListingActionUserName);
                $(".HighBidderRow").removeClass("awe-hidden");
                $(".HighBidder").pulse();
            }

            //if the current user is logged in
            @if (User.Identity.IsAuthenticated)
                {
                <text>
            //if the price update was not from an edit, and the logged in user ever placed an accepted bid, is not the high bidder or the seller (and didn't initiate the action)...
            if (anyActivity && data.Source != "UPDATE_ORIGIN" && data.UserName != "@Html.FBOUserName()" && ("@Html.FBOUserName()" != data.CurrentListingActionUserName && "@Model.OwnerUserName" != "@Html.FBOUserName()")) {
                //show generic "not winning" context alert
                var message = contextMessageDictionary["NOTCURRENTLISTINGACTIONUSER"];
                var cssClass = "alert alert-danger";
                $(".ContextualStatus").each(function () {
                    $(this).html("<div class='" + cssClass + "'>" + message + "</div>");
                    if (!$(this).is(":visible")) {
                        $(this).fadeTo(1000, 1, function () {
                            $(this).slideDown(500);
                        });
                    }
                });
            }

            </text>
                }
        });

        //if End DTTM is updated because of sniper protection, show Extended
        $(document).on("SignalR_UpdateListingDTTM", function (event, data) {
            if (data.Epoch == "ending" && (data.Source == "SOFT_ORIGIN") || data.Source == "EXTENDSINGLE_ORIGIN") {
                $(".awe-rt-Extended").show();
                $(".awe-rt-Extended").pulse();
            }
        });

        //auction specific context messages
        contextMessageDictionary["UNKNOWN"] = "@Html.Resource("AuctionListing, UNKNOWN").ToJavascriptSafeString()";
        contextMessageDictionary["LISTING_NOT_STARTED"] = "@Html.Resource("AuctionListing, LISTING_NOT_STARTED").ToJavascriptSafeString()";
        contextMessageDictionary["LISTING_DELETED"] = "@Html.Resource("AuctionListing, LISTING_DELETED").ToJavascriptSafeString()";
        contextMessageDictionary["LISTING_AWAITING_PAYMENT"] = "@Html.Resource("AuctionListing, LISTING_AWAITING_PAYMENT").ToJavascriptSafeString()";
        contextMessageDictionary["LISTING_NOT_STARTED"] = "@Html.Resource("AuctionListing, LISTING_NOT_STARTED").ToJavascriptSafeString()";
        contextMessageDictionary["WINNING"] = "@Html.Resource("AuctionListing, WINNING").ToJavascriptSafeString()";
        contextMessageDictionary["CURRENT_HIGH_BIDDER_RESERVE_NOT_MET"] = "@Html.Resource("AuctionListing, CURRENT_HIGH_BIDDER_RESERVE_NOT_MET").ToJavascriptSafeString()";
        contextMessageDictionary["LOSING"] = "@Html.Resource("AuctionListing, LOSING").ToJavascriptSafeString()";
        contextMessageDictionary["NO_ACTIVITY_AS_BUYER"] = "@Html.Resource("AuctionListing, NO_ACTIVITY_AS_BUYER").ToJavascriptSafeString()";
        contextMessageDictionary["WON"] = "@Html.Resource("AuctionListing, WON").ToJavascriptSafeString()";
        contextMessageDictionary["LOST_RESERVE_NOT_MET"] = "@Html.Resource("AuctionListing, LOST_RESERVE_NOT_MET").ToJavascriptSafeString()";
        contextMessageDictionary["LOST"] = "@Html.Resource("AuctionListing, LOST").ToJavascriptSafeString()";
        contextMessageDictionary["NO_ACTIVITY"] = "@Html.Resource("AuctionListing, NO_ACTIVITY").ToJavascriptSafeString()";
        contextMessageDictionary["NOSALE"] = "@Html.Resource("AuctionListing, NOSALE").ToJavascriptSafeString()";
        contextMessageDictionary["SOLD"] = "@Html.Resource("AuctionListing, SOLD").ToJavascriptSafeString()";
        contextMessageDictionary["NO_ACTIVITY_AS_SELLER"] = "@Html.Resource("AuctionListing, NO_ACTIVITY_AS_SELLER").ToJavascriptSafeString()";
        contextMessageDictionary["RESERVE_NOT_MET"] = "@Html.Resource("AuctionListing, RESERVE_NOT_MET").ToJavascriptSafeString()";
        contextMessageDictionary["WOULD_SELL"] = "@Html.Resource("AuctionListing, WOULD_SELL").ToJavascriptSafeString()";
        contextMessageDictionary["NOTCURRENTLISTINGACTIONUSER"] = "@Html.Resource("AuctionListing, NOTCURRENTLISTINGACTIONUSER").ToJavascriptSafeString()";

        contextMessageDictionary["ActionSuccess"] = "@Html.Resource("AuctionListing, ActionSuccess").ToJavascriptSafeString()";

        //auction specific reserve messages
        reserveStatus["NoReserve"] = "@Html.Resource("AuctionListing, NoReserve").ToJavascriptSafeString()";
        reserveStatus["ReserveNotMet"] = "@Html.Resource("AuctionListing, ReserveNotMet").ToJavascriptSafeString()";
        reserveStatus["ReserveMet"] = "@Html.Resource("AuctionListing, ReserveMet").ToJavascriptSafeString()";
    });
</script>

Developer/MVC Project/Views/Listing/FixedPriceDetails.cshtml
@model Listing

<script type="text/javascript">
    $(document).ready(function () {
        if ($.cookie('currency') == '@Model.Currency.Code') {
            $("#convertedprice").hide();
        } else {
            $("#convertedprice").show();
        }
    });
</script>
@if ((Model.Status == ListingStatuses.Successful) || (Model.Status == ListingStatuses.Unsuccessful))
{
    <div class="panel panel-default closed-details">
        <ul class="list-group">
            <li class="list-group-item">
                @Html.Resource("FixedPriceListing, ListedPrice", Html.LocalCurrencyWithNumberTags(Model.CurrentPrice.Value, Model.Currency.Code))
            </li>
            <li class="list-group-item">
                @Html.Resource("FixedPriceListing, XUnsold", Model.CurrentQuantity)
                <a href="@Url.Action(MVC.HistoryAction, "Listing", new { id = Model.ID, currency = Model.Currency.Code})" class="pull-right">
                    @Html.Resource("FixedPriceListing, ViewPurchaseHistory")
                </a>
            </li>
        </ul>
    </div>
}

@{
    bool showSellerData = bool.Parse(SiteClient.Settings["SellerUsernameDetailPage"]);
    bool paymentsEnabled = (Model.Owner.CreditCardAccepted() && SiteClient.BoolSetting(SiteProperties.AuthorizeNet_Enabled)) ||
        (Model.Owner.BoolProperty(StdUserProps.StripeConnect_SellerAccountConnected) && SiteClient.BoolSetting(SiteProperties.StripeConnect_Enabled)) ||
        (Model.OwnerAcceptsPayPal() && SiteClient.BoolSetting(SiteProperties.PayPal_Enabled));
    bool hasShipping = Model.ShippingOptions.Count > 0;
    bool hasPaymentInstructions = !string.IsNullOrEmpty(Model.PaymentInstructions());

    if (showSellerData || paymentsEnabled || hasShipping || hasPaymentInstructions)
    {
        string sellerPaymentData = "seller-data__payment";
        if (!showSellerData)
        {
            sellerPaymentData += "  seller-data__fullwidth";
        }
        <div class="detail__seller-data">
            <div class="seller-data__container">
                @{
                    if (showSellerData)
                    {
                        <div class="seller-data__summary">
                            @Html.Partial("ListingDetail_SellerUserSummary")
                        </div>
                    }
                }
                <div class="@sellerPaymentData">
                    @Html.Partial("FixedPricePaymentOptions")
                </div>
            </div>
            @Html.Partial("ShippingOptionDisplay")
        </div>
                    }
}

<script type="text/javascript">
    $(document).ready(function () {
        //when this auction's price changes
        $(document).on("SignalR_UpdateListingAction", function (event, data) {
            //if # of actions is > 0
            if (data.AcceptedActionCount > 0) {
                //show purchase history button
                $(".PurchaseHistoryButton").removeClass("awe-hidden");
            }
        });

        //if End DTTM is set to >= 80 years in future (aka Good Til Canceled/GTC) then hide the end date and start date sections
        $(document).on("SignalR_UpdateListingDTTM", function (event, data) {
            var newEndDTTM = new Date(data.DTTM);
            if (data.Epoch == "ending") {
                if (newEndDTTM.getFullYear() >= (@DateTime.UtcNow.AddYears(80).ToString("yyyy"))) {
                    $(".awe-end-dttm-container").hide();
                    $(".awe-start-dttm-container").hide();
                } else {
                    $(".awe-end-dttm-container").show();
                    $(".awe-start-dttm-container").show();
                }
            }
        });

        //auction specific context messages
        contextMessageDictionary["UNKNOWN"] = "@Html.Resource("FixedPriceListing, UNKNOWN").ToJavascriptSafeString()";
        contextMessageDictionary["LISTING_NOT_STARTED"] = "@Html.Resource("FixedPriceListing, LISTING_NOT_STARTED").ToJavascriptSafeString()";
        contextMessageDictionary["LISTING_DELETED"] = "@Html.Resource("FixedPriceListing, LISTING_DELETED").ToJavascriptSafeString()";
        contextMessageDictionary["LISTING_AWAITING_PAYMENT"] = "@Html.Resource("FixedPriceListing, LISTING_AWAITING_PAYMENT").ToJavascriptSafeString()";
        contextMessageDictionary["LISTING_NOT_STARTED"] = "@Html.Resource("FixedPriceListing, LISTING_NOT_STARTED").ToJavascriptSafeString()";
        contextMessageDictionary["BUYER_PURCHASED"] = "@Html.Resource("FixedPriceListing, BUYER_PURCHASED").ToJavascriptSafeString()";
        contextMessageDictionary["BUYER_NO_ACTIVITY"] = "@Html.Resource("FixedPriceListing, BUYER_NO_ACTIVITY").ToJavascriptSafeString()";
        contextMessageDictionary["BUYER_NO_QUANTITY_LEFT"] = "@Html.Resource("FixedPriceListing, BUYER_NO_QUANTITY_LEFT").ToJavascriptSafeString()";
        contextMessageDictionary["SELLER_ACTIVITY"] = "@Html.Resource("FixedPriceListing, SELLER_ACTIVITY").ToJavascriptSafeString()";
        contextMessageDictionary["SELLER_NO_ACTIVITY"] = "@Html.Resource("FixedPriceListing, SELLER_NO_ACTIVITY").ToJavascriptSafeString()";
        contextMessageDictionary["SELLER_SUCCESSFUL"] = "@Html.Resource("FixedPriceListing, SELLER_SUCCESSFUL").ToJavascriptSafeString()";
        contextMessageDictionary["SELLER_UNSUCCESSFUL"] = "@Html.Resource("FixedPriceListing, SELLER_UNSUCCESSFUL").ToJavascriptSafeString()";

        contextMessageDictionary["ActionSuccess"] = "@Html.Resource("FixedPriceListing, ActionSuccess").ToJavascriptSafeString()";
    });
</script>